export const SCREEN_CATALOG = [
  ['login-company', '登录与公司选择', 'auth', 'all'],
  ['workbench-employee', '员工工作台', 'workbench', 'employee'],
  ['workbench-admin', '管理员工作台', 'workbench', 'admin'],
  ['orders-current', '当前工单', 'orders', 'all'],
  ['orders-filter-sheet', '工单筛选', 'orders', 'all'],
  ['order-detail-employee', '员工工单详情', 'orders', 'employee'],
  ['order-detail-admin', '管理员工单详情', 'orders', 'admin'],
  ['order-create-customer', '新增工单：客户车辆', 'forms', 'all'],
  ['order-create-insurance', '新增工单：保险事故', 'forms', 'all'],
  ['order-create-repair', '新增工单：维修费用', 'forms', 'all'],
  ['order-create-review', '新增工单：确认提交', 'forms', 'all'],
  ['order-edit', '编辑工单', 'forms', 'all'],
  ['order-status-dialog', '状态确认', 'orders', 'all'],
  ['order-settlement', '结算工单', 'orders', 'admin'],
  ['receipt-upload', '到账回执', 'orders', 'admin'],
  ['reverse-settlement-dialog', '返结算确认', 'orders', 'admin'],
  ['records-customers', '客户车辆档案', 'records', 'all'],
  ['records-insurance', '车辆保险档案', 'records', 'all'],
  ['records-history', '维修历史', 'records', 'all'],
  ['profile-sync', '我的与同步状态', 'system', 'all'],
  ['offline-readonly', '离线只读', 'system', 'all'],
  ['states-gallery', '系统状态合集', 'system', 'all'],
].map(([id, label, group, role]) => ({ id, label, group, role }));
