export const SCREEN_CATALOG = [
  ['login-company', '鐧诲綍涓庡叕鍙搁€夋嫨', 'auth', 'all'],
  ['workbench-employee', '鍛樺伐宸ヤ綔鍙?', 'workbench', 'employee'],
  ['workbench-admin', '绠＄悊鍛樺伐浣滃彴', 'workbench', 'admin'],
  ['orders-current', '褰撳墠宸ュ崟', 'orders', 'all'],
  ['orders-filter-sheet', '宸ュ崟绛涢€?', 'orders', 'all'],
  ['order-detail-employee', '鍛樺伐宸ュ崟璇︽儏', 'orders', 'employee'],
  ['order-detail-admin', '绠＄悊鍛樺伐鍗曡鎯?', 'orders', 'admin'],
  ['order-create-customer', '鏂板宸ュ崟锛氬鎴疯溅杈?', 'forms', 'all'],
  ['order-create-insurance', '鏂板宸ュ崟锛氫繚闄╀簨鏁?', 'forms', 'all'],
  ['order-create-repair', '鏂板宸ュ崟锛氱淮淇垂鐢?', 'forms', 'all'],
  ['order-create-review', '鏂板宸ュ崟锛氱‘璁ゆ彁浜?', 'forms', 'all'],
  ['order-edit', '缂栬緫宸ュ崟', 'forms', 'all'],
  ['order-status-dialog', '鐘舵€佺‘璁?', 'orders', 'all'],
  ['order-settlement', '缁撶畻宸ュ崟', 'orders', 'admin'],
  ['receipt-upload', '鍒拌处鍥炴墽', 'orders', 'admin'],
  ['reverse-settlement-dialog', '杩旂粨绠楃‘璁?', 'orders', 'admin'],
  ['records-customers', '瀹㈡埛杞﹁締妗ｆ', 'records', 'all'],
  ['records-insurance', '杞﹁締淇濋櫓妗ｆ', 'records', 'all'],
  ['records-history', '缁翠慨鍘嗗彶', 'records', 'all'],
  ['profile-sync', '鎴戠殑涓庡悓姝ョ姸鎬?', 'system', 'all'],
  ['offline-readonly', '绂荤嚎鍙', 'system', 'all'],
  ['states-gallery', '绯荤粺鐘舵€佸悎闆?', 'system', 'all'],
].map(([id, label, group, role]) => ({ id, label, group, role }));
